### ISSUE TITLE
Do we support other Ubuntu version than Ubuntu LTS?

### ISSUE THREAD

**Issue by kri5** [justincampbell/chef-drone#28]
In the kitchen tests, we test against 12.04, 13.10 and 14.04.

Should we drop all the non LTS releases of ubuntu? or do we want to support all versions, in which case we are missing some targets.

**Comment by shawnzhu** [comment]
No, I don't think we should support those release has end of life, like Ubuntu 13.10. the reason is simple, `apt-get update` fails because of repo is not supported, one can install nothing.

@justincampbell I propose removing ubuntu 13.10 from supported list since it has [end of life since July 17, 2014](http://fridge.ubuntu.com/2014/07/17/ubuntu-13-10-saucy-salamander-end-of-life-reached-on-july-17-2014/) what do you think?

**Comment by justincampbell** [comment]
@shawnzhu I'm :+1: on dropping support for EOL OS/Ruby/Chef versions

**Comment by shawnzhu** [comment]
closed since ubuntu 13.10 is excluded.
